export type ReportMode = "technical" | "plain";

export interface ProgressStage {
  id: string;
  label: string;
}

export type StreamEvent<T> =
  | { type: "stage"; stage: ProgressStage }
  | { type: "result"; data: T }
  | { type: "error"; error: string };

export interface Problem {
  issue: string;
  plainIssue: string;
  impact: "High" | "Medium" | "Low";
  effort: "Easy" | "Medium" | "Hard";
}

export interface CodeSnippet {
  language: string;
  code: string;
}

export interface ActionItem {
  text: string;
  plainText: string;
  snippet: CodeSnippet | null;
}

/**
 * Prefer `-latest` aliases over pinned versions. Pinned model ids are retired without
 * warning — `gemini-2.5-flash` now returns 404 — which would take the primary model out
 * silently. `gemini-3.5-flash-lite` is the one pinned entry, kept as a middle fallback.
 */
export type GeminiModel =
  | "gemini-flash-lite-latest"
  | "gemini-3.5-flash-lite"
  | "gemini-flash-latest";

/** A single element of the Gemini `contents[0].parts` array. */
export type GeminiPart =
  | { text: string }
  | { inline_data: { mime_type: string; data: string } };

export type CheckStatus = "pass" | "warn" | "fail";

/**
 * Most checks derive from `<head>` metadata (plus the URL's scheme and `<html lang>`) —
 * server-rendered by necessity, since that's what crawlers and social-card scrapers read,
 * so trustworthy even on the raw-fetch (unrendered) path.
 *
 * `h1`/`altText` are the exception: they're body-DOM facts, reinstated now that the
 * scraper computes them from the live, rendered, hidden-content-stripped page — `h1`
 * from its Cheerio metadata pass, `altText` from a `page.evaluate()` read that also
 * confirms each image actually loaded (`naturalWidth > 0`), which a static HTML parse
 * can never know. Both are only trusted when `isVerified` (the `scraper-html` path) —
 * on raw-fetch, an SPA's body may not exist yet, which is exactly why these were removed
 * in the first place.
 */
export interface SeoCheck {
  id:
    | "https"
    | "noindex"
    | "metaDescription"
    | "title"
    | "viewport"
    | "zoomBlocked"
    | "canonical"
    | "socialPreview"
    | "favicon"
    | "langAttribute"
    | "h1"
    | "altText";
  status: CheckStatus;
  pointsDeducted: number;
  // Raw facts only (numbers/booleans/strings) — prose is built at render time
  // from these values, never stored here, so plain/technical copy can never
  // drift from what was actually verified.
  values: Record<string, string | number | boolean | null>;
}

/** One `<img>` as read live from the rendered DOM — see `extractDomFacts` in scrape.js. */
export interface DomImage {
  src: string;
  /** `null` when the element has no `alt` attribute at all — see `hasAltAttribute`. */
  alt: string | null;
  /** Distinguishes "no alt attribute" (missing) from `alt=""` (deliberately decorative). */
  hasAltAttribute: boolean;
  /** 0 after the page has settled means the image never loaded — a genuinely broken image. */
  naturalWidth: number;
  naturalHeight: number;
}

/** One `<a href>` as read live from the rendered DOM, with a browser-computed accessible name. */
export interface DomLink {
  /** Already resolved to an absolute URL by the browser — no relative/absolute ambiguity. */
  href: string;
  /** textContent → aria-label → title → inner img alt → inner svg <title>, in that order. */
  accessibleName: string;
}

/**
 * News-vs-storefront signals from the scraper's JSON-LD scan, used to skip
 * pricing/guarantee/payment checks on sites that were never selling anything in the
 * first place (see `isLikelyContentSite`/`isLikelyCommerceSite` in contentChecks.ts).
 */
export interface CommerceSignals {
  hasProductSchema: boolean;
  hasNewsSchema: boolean;
  hasCommerceButtons: boolean;
}

export interface SeoChecks {
  checks: SeoCheck[];
  seoScore: number;
  isVerified: boolean;
}

export interface SeoFacts {
  hasHttps: boolean;
  title: string | null;
  titleLength: number;
  /** Title left at a framework/CMS default ("Home", "Create Next App", "Untitled"). */
  titleIsGeneric: boolean;
  metaDescription: string | null;
  metaDescriptionLength: number;
  /** A platform default nobody wrote on purpose ("Generated by create next app"). */
  metaDescriptionIsGeneric: boolean;
  viewportPresent: boolean;
  canonicalPresent: boolean;
  isVerified: boolean;

  /**
   * The combined `robots` + `googlebot` meta directives, verbatim. Note this cannot see
   * an `X-Robots-Tag` HTTP header, so a page can be de-indexed in a way we can't detect —
   * absence of noindex here is "no noindex in the HTML", not proof the page is indexable.
   */
  robotsDirectives: string | null;
  /** The single most damaging finding available from markup: invisible to search. */
  isNoindex: boolean;

  /** Open Graph tags — what a link to this page looks like when shared. */
  ogTitle: string | null;
  ogDescription: string | null;
  ogImage: string | null;

  /** The viewport tag's raw content, so the report can quote what's actually set. */
  viewportContent: string | null;
  /** `user-scalable=no` / `maximum-scale=1` — blocks pinch-zoom, a WCAG failure. */
  viewportBlocksZoom: boolean;

  /** `<html lang>` — screen readers use it to pick a pronunciation. */
  langAttribute: string | null;

  faviconPresent: boolean;

  /**
   * From the scraper's Cheerio metadata pass (over the rendered, hidden-stripped page),
   * not from `<head>` — see the `SeoCheck` doc comment for why this one check is an
   * exception to the head-only rule. `null` when the scraper didn't report it (an older
   * deployment, or the raw-fetch path, which has no rendered DOM to count at all).
   */
  h1Count: number | null;

  /**
   * Every `<img>` on the rendered, hidden-content-stripped page, read live via
   * `page.evaluate()` in the scraper — `null` on the raw-fetch path or an older scraper
   * deployment that doesn't send it. See `DomImage` for why this can't come from a
   * static HTML parse.
   */
  domImages: DomImage[] | null;
}

/**
 * Binary, because the old good/adequate/poor scale was the dominant remaining variance
 * source: "adequate" absorbed all uncertainty and the good/adequate line was pure taste.
 * "unclear" is not a middle grade — it is excluded from scoring entirely (see
 * computeCategoryScore), so hedging can neither help nor hurt a site's score.
 */
export type CriterionRating = "yes" | "no" | "unclear";

/**
 * How sure a "yes" actually is. Exists because a regex finding an email-shaped string is
 * not the same claim as finding a real `mailto:` link — Stripe's own demo email
 * ("jane.diaz@stripe.com", a real string on their real domain, not a way to contact
 * them) is exactly the case this distinguishes. Only meaningful when `rating === "yes"`;
 * absent (not just "high") for the ~150 other criteria that have no such ambiguity.
 * See `computeCategoryScore` for how this affects the actual score, not just the wording.
 */
export type CriterionConfidence = "high" | "medium" | "low";

export interface CriterionResult {
  id: string;
  rating: CriterionRating;
  /** Short observation the rating is based on — forces grounding before judging. */
  evidence: string;
  confidence?: CriterionConfidence;
}

/**
 * One subjective category. The model supplies ratings for the AI-tier criteria and
 * contentChecks.ts supplies the code tier; `score` is computed from both in code, so no
 * number is ever invented.
 */
export interface CategoryAssessment {
  category: "design" | "trust" | "ux";
  score: number;
  criteria: CriterionResult[];
}

export interface Report {
  overallScore: number;
  firstImpression: string;
  plainFirstImpression: string;
  designScore: number;
  trustScore: number;
  uxScore: number;
  seoScore: number;
  seoChecks: SeoChecks;
  /** Per-criterion breakdown behind designScore/trustScore/uxScore. */
  assessments: CategoryAssessment[];
  modelUsed: GeminiModel;
  biggestProblems: Problem[];
  quickWins: ActionItem[];
  suggestions: ActionItem[];
}

export type ComparisonWinner = "yours" | "competitor" | "tie";

export interface SiteSummary {
  url: string;
  overallScore: number;
  firstImpression: string;
  plainFirstImpression: string;
  strengths: string[];
  plainStrengths: string[];
  weaknesses: string[];
  plainWeaknesses: string[];
}

export interface ComparisonCategory {
  category: "Design" | "Trust" | "UX" | "SEO";
  yourScore: number;
  competitorScore: number;
  winner: ComparisonWinner;
  verdict: string;
  plainVerdict: string;
}

export interface ComparisonReport {
  yours: SiteSummary;
  competitor: SiteSummary;
  categories: ComparisonCategory[];
  yourSeoChecks: SeoChecks;
  competitorSeoChecks: SeoChecks;
  overallWinner: ComparisonWinner;
  overallVerdict: string;
  plainOverallVerdict: string;
  topRecommendations: string[];
  plainTopRecommendations: string[];
  modelUsed: GeminiModel;
}
